//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sob213_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST
    {
        public int ID { get; set; }
        public int EMP_ID { get; set; }
        public string NEW_EMAIL { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
